using System.Text;
using Rymote.Reflex.Generators.Analysis;

namespace Rymote.Reflex.Generators.Emission;

internal static class PartialEmitter
{
    internal static string Emit(ReactiveTypeModel typeModel)
    {
        StringBuilder builder = new();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.Append("namespace ").Append(typeModel.NamespaceName).AppendLine(";");
        builder.AppendLine();
        builder.Append("partial class ").Append(typeModel.ClassName)
               .AppendLine(" : global::Rymote.Reflex.Utilities.IReactive");
        builder.AppendLine("{");

        // Emit DependencySlot fields for partial TrackedAuto and TrackedNestedReactive properties
        foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
        {
            if (!propertyModel.IsPartialDeclaration) continue;
            if (propertyModel.Kind != ReactivePropertyKind.TrackedAuto
                && propertyModel.Kind != ReactivePropertyKind.TrackedNestedReactive) continue;
            string backingFieldName = $"_{ToCamelCase(propertyModel.PropertyName)}";
            string slotFieldName = $"{backingFieldName}Slot";

            builder.Append("    private readonly global::Rymote.Reflex.Core.DependencySlot ")
                   .Append(slotFieldName).AppendLine(" = new();");
        }

        bool hasAnyPartialTrackedAutoOrNested = false;
        foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
        {
            if (propertyModel.IsPartialDeclaration
                && (propertyModel.Kind == ReactivePropertyKind.TrackedAuto
                    || propertyModel.Kind == ReactivePropertyKind.TrackedNestedReactive))
            {
                hasAnyPartialTrackedAutoOrNested = true;
                break;
            }
        }

        if (hasAnyPartialTrackedAutoOrNested)
            builder.AppendLine("    private readonly object _trackedFieldLock = new();");

        // Emit backing fields for partial TrackedAuto and TrackedNestedReactive
        foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
        {
            if (!propertyModel.IsPartialDeclaration) continue;
            if (propertyModel.Kind != ReactivePropertyKind.TrackedAuto
                && propertyModel.Kind != ReactivePropertyKind.TrackedNestedReactive) continue;
            string backingFieldName = $"_{ToCamelCase(propertyModel.PropertyName)}";
            string initializerSuffix = propertyModel.HasInitializer
                ? $" = {propertyModel.InitializerExpression};"
                : " = default!;";
            builder.Append("    private ").Append(propertyModel.DeclaredTypeFullName).Append(' ')
                   .Append(backingFieldName).Append(initializerSuffix).AppendLine();
        }

        // Emit partial property implementations for TrackedAuto and TrackedNestedReactive
        foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
        {
            if (!propertyModel.IsPartialDeclaration) continue;
            if (propertyModel.Kind != ReactivePropertyKind.TrackedAuto
                && propertyModel.Kind != ReactivePropertyKind.TrackedNestedReactive) continue;
            string backingFieldName = $"_{ToCamelCase(propertyModel.PropertyName)}";
            string slotFieldName = $"{backingFieldName}Slot";

            builder.AppendLine();
            builder.Append("    public partial ").Append(propertyModel.DeclaredTypeFullName).Append(' ')
                   .Append(propertyModel.PropertyName).AppendLine();
            builder.AppendLine("    {");
            builder.AppendLine("        get");
            builder.AppendLine("        {");
            builder.Append("            ").Append(slotFieldName).AppendLine(".RegisterCurrentEffectAsDependent();");
            builder.Append("            lock (_trackedFieldLock) return ").Append(backingFieldName).AppendLine(";");
            builder.AppendLine("        }");
            builder.AppendLine("        set");
            builder.AppendLine("        {");
            builder.AppendLine("            bool valueChanged;");
            builder.AppendLine("            lock (_trackedFieldLock)");
            builder.AppendLine("            {");
            builder.Append("                valueChanged = !global::System.Collections.Generic.EqualityComparer<")
                   .Append(propertyModel.DeclaredTypeFullName).Append(">.Default.Equals(")
                   .Append(backingFieldName).AppendLine(", value);");
            builder.Append("                if (valueChanged) ").Append(backingFieldName).AppendLine(" = value;");
            builder.AppendLine("            }");
            builder.Append("            if (valueChanged) ").Append(slotFieldName).AppendLine(".NotifyAllSubscribers();");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
        }

        // Emit TrackedComputed backing fields (partial computed properties)
        bool hasAnyComputedProperty = false;
        foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
        {
            if (propertyModel.Kind == ReactivePropertyKind.TrackedComputed)
            {
                hasAnyComputedProperty = true;
                break;
            }
        }

        if (hasAnyComputedProperty)
        {
            foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
            {
                if (propertyModel.Kind != ReactivePropertyKind.TrackedComputed) continue;
                string computedFieldName = $"_{ToCamelCase(propertyModel.PropertyName)}Computed";
                builder.AppendLine();
                builder.Append("    private readonly global::Rymote.Reflex.Primitives.Computed<")
                       .Append(propertyModel.DeclaredTypeFullName).Append("> ")
                       .Append(computedFieldName).AppendLine(";");
            }

            builder.AppendLine();
            builder.Append("    public ").Append(typeModel.ClassName).AppendLine("()");
            builder.AppendLine("    {");
            foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
            {
                if (propertyModel.Kind != ReactivePropertyKind.TrackedComputed) continue;
                string computedFieldName = $"_{ToCamelCase(propertyModel.PropertyName)}Computed";
                builder.Append("        ").Append(computedFieldName)
                       .Append(" = new global::Rymote.Reflex.Primitives.Computed<")
                       .Append(propertyModel.DeclaredTypeFullName).Append(">(this.Compute")
                       .Append(propertyModel.PropertyName).AppendLine(");");
            }
            builder.AppendLine("    }");

            foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
            {
                if (propertyModel.Kind != ReactivePropertyKind.TrackedComputed) continue;
                string computedFieldName = $"_{ToCamelCase(propertyModel.PropertyName)}Computed";
                builder.AppendLine();
                builder.Append("    public partial ").Append(propertyModel.DeclaredTypeFullName).Append(' ')
                       .Append(propertyModel.PropertyName).Append(" => ").Append(computedFieldName).AppendLine(".Value;");
            }
        }

        // Emit TrackedCollection wrapper fields and properties (partial declarations)
        foreach (ReactivePropertyModel propertyModel in typeModel.Properties)
        {
            if (!propertyModel.IsPartialDeclaration) continue;
            if (propertyModel.Kind != ReactivePropertyKind.TrackedCollection) continue;

            string fullyQualifiedCollectionType = propertyModel.DeclaredTypeFullName;
            string wrapperType;
            string interfaceType;
            if (fullyQualifiedCollectionType.StartsWith("global::System.Collections.Generic.List<"))
            {
                string itemType = ExtractFirstGenericArgument(fullyQualifiedCollectionType);
                wrapperType = $"global::Rymote.Reflex.Collections.ReactiveListWrapper<{itemType}>";
                interfaceType = $"global::System.Collections.Generic.IList<{itemType}>";
            }
            else if (fullyQualifiedCollectionType.StartsWith("global::System.Collections.Generic.Dictionary<"))
            {
                (string keyType, string valueType) = ExtractTwoGenericArguments(fullyQualifiedCollectionType);
                wrapperType = $"global::Rymote.Reflex.Collections.ReactiveDictionaryWrapper<{keyType}, {valueType}>";
                interfaceType = $"global::System.Collections.Generic.IDictionary<{keyType}, {valueType}>";
            }
            else
            {
                string itemType = ExtractFirstGenericArgument(fullyQualifiedCollectionType);
                wrapperType = $"global::Rymote.Reflex.Collections.ReactiveSetWrapper<{itemType}>";
                interfaceType = $"global::System.Collections.Generic.ISet<{itemType}>";
            }

            string backingFieldName = $"_{ToCamelCase(propertyModel.PropertyName)}Wrapper";
            string initializerSegment = propertyModel.HasInitializer
                ? propertyModel.InitializerExpression!
                : "new()";

            builder.AppendLine();
            builder.Append("    private ").Append(wrapperType).Append(' ')
                   .Append(backingFieldName).Append(" = new ").Append(wrapperType).Append('(')
                   .Append(initializerSegment).AppendLine(");");

            builder.Append("    public partial ").Append(interfaceType).Append(' ')
                   .Append(propertyModel.PropertyName).AppendLine();
            builder.AppendLine("    {");
            builder.Append("        get => ").Append(backingFieldName).AppendLine(";");
            builder.Append("        set => ").Append(backingFieldName)
                   .Append(" = new ").Append(wrapperType).AppendLine("(value);");
            builder.AppendLine("    }");
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string ToCamelCase(string pascalCaseName)
    {
        if (pascalCaseName.Length == 0) return pascalCaseName;
        return char.ToLowerInvariant(pascalCaseName[0]) + pascalCaseName.Substring(1);
    }

    private static string ExtractFirstGenericArgument(string fullyQualifiedGenericTypeName)
    {
        int openAngleIndex = fullyQualifiedGenericTypeName.IndexOf('<');
        int closeAngleIndex = fullyQualifiedGenericTypeName.LastIndexOf('>');
        return fullyQualifiedGenericTypeName.Substring(openAngleIndex + 1, closeAngleIndex - openAngleIndex - 1).Trim();
    }

    private static (string, string) ExtractTwoGenericArguments(string fullyQualifiedGenericTypeName)
    {
        string inside = ExtractFirstGenericArgument(fullyQualifiedGenericTypeName);
        int splitIndex = FindTopLevelCommaIndex(inside);
        string keyArgument = inside.Substring(0, splitIndex).Trim();
        string valueArgument = inside.Substring(splitIndex + 1).Trim();
        return (keyArgument, valueArgument);
    }

    private static int FindTopLevelCommaIndex(string genericArgumentList)
    {
        int nestingDepth = 0;
        for (int charIndex = 0; charIndex < genericArgumentList.Length; charIndex++)
        {
            char currentCharacter = genericArgumentList[charIndex];
            if (currentCharacter == '<') nestingDepth++;
            else if (currentCharacter == '>') nestingDepth--;
            else if (currentCharacter == ',' && nestingDepth == 0) return charIndex;
        }
        return -1;
    }
}
